version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: "./cmd/commity"
    binary: commity
    ldflags:
      - "-X 'main.VERSION={{.Version}}'"


archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"



nfpms:
  - id: commity
    package_name: commity
    file_name_template: "{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Michael Rampl
    homepage: https://github.com/michaelrampl/commity
    maintainer: Michael Rampl <info@michael-rampl.com>
    description: |-
      Make commit messages fun again
    license: WTFPL
    formats:
      - deb
      - rpm
    dependencies:
      - git
