name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...

    - name: Build binaries
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build ./cmd/commity/ -o dist/commity-linux-amd64
        GOOS=windows GOARCH=amd64 go build ./cmd/commity/ -o dist/commity-windows-amd64.exe
        GOOS=darwin GOARCH=amd64 go build ./cmd/commity/ -o dist/commity-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build ./cmd/commity/ -o dist/commity-darwin-arm64

    - name: Upload Release Assets
      uses: actions/upload-artifact@v3
      with:
        name: commity-binaries
        path: dist/
