name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

    - name: Build binaries
      run: |
        mkdir -p dist
        VERSION=${{ github.ref_name }}
        GOOS=linux GOARCH=amd64 go build -o dist/commity-linux-amd64-${VERSION} ./cmd/commity/
        GOOS=windows GOARCH=amd64 go build -o dist/commity-windows-amd64-${VERSION}.exe ./cmd/commity/
        GOOS=darwin GOARCH=amd64 go build -o dist/commity-darwin-amd64-${VERSION} ./cmd/commity/
        GOOS=darwin GOARCH=arm64 go build -o dist/commity-darwin-arm64-${VERSION} ./cmd/commity/

    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/commity-linux-amd64-${{ github.ref_name }}
        asset_name: commity-linux-amd64-${{ github.ref_name }}
        asset_content_type: application/octet-stream

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/commity-windows-amd64-${{ github.ref_name }}.exe
        asset_name: commity-windows-amd64-${{ github.ref_name }}.exe
        asset_content_type: application/octet-stream

    - name: Upload macOS Binary (amd64)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/commity-darwin-amd64-${{ github.ref_name }}
        asset_name: commity-darwin-amd64-${{ github.ref_name }}
        asset_content_type: application/octet-stream

    - name: Upload macOS Binary (arm64)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/commity-darwin-arm64-${{ github.ref_name }}
        asset_name: commity-darwin-arm64-${{ github.ref_name }}
        asset_content_type: application/octet-stream

