name: Release


on:
  release:
    types:
      - published


jobs:

  build:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Tidy dependencies
      run: go mod tidy

    - name: Run tests
      run: go test -v ./...

#    - name: Build binaries
#      run: |
#        mkdir -p dist
#        VERSION=${{ github.ref_name }}
#        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/commity-linux-amd64-${VERSION} ./cmd/commity/
#        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o dist/commity-windows-amd64-${VERSION}.exe ./cmd/commity/
#        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o dist/commity-darwin-amd64-${VERSION} ./cmd/commity/
#        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o dist/commity-darwin-arm64-${VERSION} ./cmd/commity/

#    - name: Upload Release Assets
#      uses: softprops/action-gh-release@v1
#      with:
#        files: dist/*
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}